### PR TITLE
Added the output template setting

### PR DESCRIPTION
**Pull request by tht7**
Added the output template setting and a "force" override to the default templates (the site specific templates)

### CODE REVIEW

**Comment by zxzzz8** [comment]
solves in https://github.com/section83/MacYTDL/issues/9 7=''Enable custom file name formats to be set by the user ?'',
and hopefully my issue w https://github.com/section83/MacYTDL/issues/30 i take it? ^^

oh wait my issue still also need another thing, mby the ''-2'' at the end of the file, or ask the user what to do, when the user doesn't set a good template that make a difference between 2 files in such a batch, just in case, for being a complete polished app solution.... but thats more polishing as this is the main solution here i think =3

**Comment by section83** [comment]
Many thanks for all this.  It should give us a leg up to adding the feature.

I've been thinking of adding the custom file name template to "Settings".  There, users would be able to enter and save the template and turn it on/off with a checkbox.  After that, need to change a number of handlers: set_preferences, add_v1_18_preference, read_settings, set_File_Names, download_video and download_batch.  The only tricky changes are in set_File_Names, download_video and download_batch as it involves playing with existing logic.

Also, might add this as a "One-time" setting (in main_dialog) so that it's easy to change the template for individual downloads without losing the saved template.

It might take me a while to get my head around it all.  I'll be in touch.

Cheers.

**Comment by section83** [comment]
By the way, I've a few changes already made which I've not copied to GitHub.  So, there's unrelated code you've not seen.

Do you use Script Debugger ?  If so, can you integrate it with GitHub ?  So far, I've found GitHub plays badly with AppleScript.  Also, it takes 1-2 minutes for Safari to show a file in your commit - or do/show anything in a pull request.  It's slower than the proverbial (insert favourite line here).  Anyway, I'll try to upload what I've done in v1.18 so you can see the changes – might be a few hours.

**Comment by tht7** [comment]
> I've been thinking of adding the custom file name template to "Settings". There, users would be able to enter and save the template and turn it on/off with a checkbox. After that, need to change a number of handlers: set_preferences, add_v1_18_preference, read_settings, set_File_Names, download_video and download_batch. The only tricky changes are in set_File_Names, download_video and download_batch as it involves playing with existing logic.

That's basically what I've done :) 
I added the File name template to the settings panel and a checkbox to "always override" the default templates (the site specific)

I've also "updated" the preferences file to v17.1**.1**
And I've tested it all in the editor :)

the only thing I know might break is the conflict resolution code, there you relay on the end of the default filename template (you replace "title)s" for "title)s-2" but the user might have removed the title from the template all together)

But this is an easy fix (I just forgot to push it 😅 )  just replace the ext (since the ext)s is always gruaranteed it exists, 
just replace ".%(ext)s" with "-2.%(ext)s")

**Comment by section83** [comment]
> But this is an easy fix (I just forgot to push it 😅 ) just replace the ext (since the ext)s is always gruaranteed it exists,
just replace ".%(ext)s" with "-2.%(ext)s")

Of course, I should have done that in the first place.  Anyway, now that thumbnails are "fixed", I can move on.

The "Settings" dialog is getting long.  It might be too long for my 720p TV so, I'm looking at options like separate Settings dialogs for different kinds of settings etc.  I'm adding more YTDL options that people have asked for in other GUIs (e.g. cookies, .netrc, video passwords).

Cheers.

**Comment by section83** [comment]
Custom output template now implemented.

**Pull request closed without merging**
